# このファイルはバックアップ用の設定ファイルです。実際に設定を行う際は、`config.yml`を使用してください。
backend:
  name: git-gateway
  branch: master # デフォルトブランチ名

# メディアファイルの設定
media_folder: "public/images/uploads" # メディアファイルの保存先
public_folder: "/images/uploads" # 公開URLパス

# ローカル開発用設定
local_backend: true

# コレクション（コンテンツタイプ）の定義
collections:
  # お知らせ
  - name: "announcements"
    label: "お知らせ"
    folder: "content/announcements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "発行日", name: "date", widget: "datetime"}
      - {label: "タイプ", name: "type", widget: "select", options: ["important", "normal", "pickup"], default: "normal"}
      - {label: "概要", name: "description", widget: "text"}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "公開", name: "published", widget: "boolean", default: true}

  # 生活・くらし
  - name: "lifestyle"
    label: "生活・くらし"
    folder: "content/lifestyle"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["housing", "farming", "cooking", "building", "rules"], default: "housing"}
      - {label: "順序", name: "order", widget: "number", default: 0}
      - {label: "概要", name: "description", widget: "text"}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "公開", name: "published", widget: "boolean", default: true}

  # 経済
  - name: "economy"
    label: "経済"
    folder: "content/economy"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["earn", "spend", "market", "shops", "currency"], default: "earn"}
      - {label: "順序", name: "order", widget: "number", default: 0}
      - {label: "概要", name: "description", widget: "text"}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "公開", name: "published", widget: "boolean", default: true}

  # 娯楽
  - name: "entertainment"
    label: "娯楽"
    folder: "content/entertainment"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["games", "events", "contests", "sports", "activities"], default: "games"}
      - {label: "順序", name: "order", widget: "number", default: 0}
      - {label: "概要", name: "description", widget: "text"}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "公開", name: "published", widget: "boolean", default: true}

  # 観光
  - name: "tourism"
    label: "観光"
    folder: "content/tourism"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["landmarks", "museums", "parks", "buildings", "monuments"], default: "landmarks"}
      - {label: "順序", name: "order", widget: "number", default: 0}
      - {label: "概要", name: "description", widget: "text"}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "アイキャッチ画像", name: "image", widget: "image", required: false}
      - {label: "公開", name: "published", widget: "boolean", default: true}

  # 交通
  - name: "transportation"
    label: "交通"
    folder: "content/transportation"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["trains", "roads", "boats", "teleport", "maps"], default: "trains"}
      - {label: "順序", name: "order", widget: "number", default: 0}
      - {label: "概要", name: "description", widget: "text"}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "路線図・地図", name: "map_image", widget: "image", required: false}
      - {label: "公開", name: "published", widget: "boolean", default: true}

  # ページ設定
  - name: "pages"
    label: "ページ設定"
    files:
      - label: "トップページ"
        name: "homepage"
        file: "content/pages/homepage.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "説明", name: "description", widget: "text"}
          - {label: "スライダー画像1", name: "slide1_image", widget: "image", required: false}
          - {label: "スライダー画像2", name: "slide2_image", widget: "image", required: false}
          - {label: "スライダー画像3", name: "slide3_image", widget: "image", required: false}

# 日本語対応
locale: 'ja'

# プレビュー設定
show_preview_links: false

# サイト設定
site_url: https://ineserver.netlify.app # 実際のサイトURLに変更してください
